Repository cisagov/pe-reports, pull requests merged in 2021-09, with the labels that each got.

#47 Add credential exposure tables and adjust foreign keys
  src/pe_reports/data/data_schema.sql
Labels: documentation

#44 Clean up pages.py charts and text inserts
  src/pe_reports/pages.py
Labels: improvement

#43 Add dark web schema to sql
  src/pe_reports/data/data_schema.sql
Labels: documentation, improvement

#58 add organization to the data schema for hibp
  src/pe_reports/data/data_schema.sql
Labels: improvement

#60 Correct FK column name errors in SQL Script
  src/pe_reports/data/data_schema.sql
Labels: bug

#70 Fix syntax/naming errors in PE data schema
  src/pe_reports/data/data_schema.sql
Labels: documentation, improvement
