Repository cisagov/pe-reports, pull requests merged in 2023-03, with the labels that each got.

#427 Add WAS table schema
  src/pe_reports/data/data_schema.sql
Labels: Draft PR

#482 Update WAS table to add columns
  src/pe_reports/data/data_schema.sql
Labels: improvement, upstream update, High Priority

#414 Add intelX scan to Pe_source
  src/pe_reports/data/database.ini
  src/pe_source/data/pe_db/config.py
  src/pe_source/data/pe_db/db_query_source.py
  src/pe_source/intelx_identity.py
  src/pe_source/pe_scripts.py
Labels: improvement, upstream update, Draft PR
